### ISSUE TITLE
Simple Dice Roller not working on Foundry v9 Stable 3

### ISSUE THREAD

**Issue by everyonecancode** [jopeek/fvtt-simple-dice-roller#14] opened 2022-03-03 07:02 UTC
After updating to most recent version of foundry Simple Dice Roller no longer works. It is shown at the edge of the screen correctly, shows dice that can be rolled, but does not respond to clicking on anything. No dice can be thrown.

Tested on: Foundry v9 Stable 3
Simple Dice Roller version: 1.3.4
Other modules loaded: No
Tested on: Linux Brave (Chromium), Windows Brave, Windows Edge, Windows Firefox

Tested for both GM and Player.

Screenshot:
![image](https://user-images.githubusercontent.com/15422337/156513239-87978526-93fe-4d9f-a6c6-497fa6755798.png)
 
1: Dices can be seen, but cannot be clicked

Logs:
No errors present.

**Comment by Someone2345** [comment] 2022-03-03 20:25
yup - witnessed too since update - exactly as described. 
Ubuntu Server - Windows 10 Edge and Chrome client access.

**Comment by paercebal** [comment] 2022-03-03 20:43
Confirmed on Windows server, + Firefox & Chrome clients on Windows.
Also, is it me, or isn't the background missing, somehow?
![image](https://user-images.githubusercontent.com/15169954/156649341-8fe2b68d-9e13-45f6-93be-656c155bafad.png)

**Comment by jopeek** [comment] 2022-03-03 20:45
Confirmed new bug with the latest FoundryVTT. Looking into it.

**Comment by jopeek** [comment] 2022-03-03 20:53
Fixed in 1.3.5

**Closed by jopeek** 2022-03-03 20:53 UTC
Labels: bug

**Comment by Someone2345** [comment] 2022-03-03 20:59
Good work - all better now :)
Many thanks

**Comment by everyonecancode** [comment] 2022-03-04 06:07
Works like a charm :). Thank you!
